"use server";

import { getServerSession } from "next-auth/next";
import { authOptions } from "../../lib/auth";
import prisma from "@repo/db/client";

export async function createOnRampTxn(amount: number, provider: string) {
    const session= await getServerSession(authOptions);
    const userId=session.user.id;

   // token=await axios.get("hdfcbank.com/api/getToken");

    if(!userId) {
        throw new Error("Unauthorized");
    }
    const txn= await prisma.onRampTransaction.create({
        data: {
            userId: Number(userId),
            amount:amount,
            provider:provider,
            status:"Processing",
            startTime: new Date(),
            //in real world scenario, token should be generated by the provider and should be unique for each transaction. Here we are using randomUUID for demo purposes.
            token: crypto.randomUUID().toString()
        }
    });
    return{
        message: "Transaction created",
    };
}