import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./components/providers";
import { AppbarClient } from "./components/AppbarClient";
// import {Provider} from "react-redux";
// import { store } from "@repo/store/store";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       {/* <Provider store={store}> */}
       <Providers>
        <AppbarClient />
        {children}
        </Providers>
       {/* </Provider> */}
        
      </body>
    </html>
  );
}
